language: python
python:
  - 2.7
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libblas-dev gfortran
 - sudo apt-get install -qq python-numpy python-scipy
 - sudo apt-get install uuid-dev
 - wget http://download.zeromq.org/zeromq-2.2.0.tar.gz && tar xf zeromq-2.2.0.tar.gz && cd zeromq-2.2.0 && ./configure && make && sudo make install
 - sudo pip install pyzmq
 - sudo pip install quantities
install:
  - sudo pip install Theano
  - ls -latr /usr/local/lib/python2.7/dist-packages/
  - PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages/
  - PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages/theano/
  - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
  - export PYTHONPATH
script:
  - cd .. && make test
