language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pyzmq
  - pip install numpy
  - pip install scipy
  - pip install Theano
script:
  - test/unit-tests.sh
